# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.18.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(scheme: "qollie")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do

    increment_build_number

    gym(scheme: "qollie", include_bitcode: true, clean: true)
    deliver(force: true,skip_screenshots: true)

    crashlytics(
              api_token: "ae32a781ec002f65fd6900f49c380cfbd17c7b86",
              build_secret: "09bcff82aded0899fc4aa8ed539984fd3275dc66aa2bbb4e306718c01aba3668",
              groups: ["ALL"],
              notes: "Distributed with fastlane", # Check out the changelog_from_git_commits action
              notifications: false
              )

    # get version and build numbers
    version = get_version_number()
    build = get_build_number()
    tag = version + "b" + build

    # commit
    commit_version_bump(xcodeproj: "./qollie.xcodeproj",force: true)

    # add tag
    add_git_tag(tag: tag)

    # push
    push_to_git_remote
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
